name: nf-core Docker push (release)
# This builds the docker image and pushes it to DockerHub
# Runs on nf-core repo releases and push event to 'dev' branch (PR merges)
on:
  release:
    types: [published]

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub (release)
    runs-on: ubuntu-latest
    # Only run for the nf-core repo, for releases and merged PRs
    if: ${{ github.repository == 'nf-core/tools' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build new docker image
        run: |
          docker build --no-cache . -t nfcore/tools:latest
          docker build --no-cache nf_core/gitpod/gitpod.Dockerfile -t nfcore/gitpod:latest

      - name: Push Docker image to DockerHub (release)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push nfcore/tools:latest
          docker tag nfcore/tools:latest nfcore/tools:${{ github.event.release.tag_name }}
          docker push nfcore/tools:${{ github.event.release.tag_name }}
          docker push nfcore/gitpod:latest
          docker tag nfcore/gitpod:latest nfcore/tools:${{ github.event.release.tag_name }}
          docker push nfcore/gitpod:${{ github.event.release.tag_name }}
